// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbFimage.* name the application
// calls that HbFimage.cs does not implement. Each throws at call time.
// Implement the function in HbFimage.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbFimage
{
}
