// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbZebra.* name the application
// calls that HbZebra.cs does not implement. Each throws at call time.
// Implement the function in HbZebra.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbZebra
{
    public static dynamic hb_zebra_create_code128(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_code128));
    public static dynamic hb_zebra_create_code39(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_code39));
    public static dynamic hb_zebra_create_ean13(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_ean13));
    public static dynamic hb_zebra_create_ean8(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_ean8));
    public static dynamic hb_zebra_create_itf(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_itf));
    public static dynamic hb_zebra_create_qrcode(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_create_qrcode));
    public static dynamic hb_zebra_destroy(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_destroy));
    public static dynamic hb_zebra_geterror(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zebra_geterror));
}
