// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbSqlit3.* name the application
// calls that HbSqlit3.cs does not implement. Each throws at call time.
// Implement the function in HbSqlit3.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbSqlit3
{
}
