#!/bin/bash
# Run all transpiler tests
# Usage: ./runtests.sh [path-to-hbtranspiler]

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
ROOTDIR="$(cd "$SCRIPTDIR/../../.." && pwd)"
TRANSPILER="${1:-$ROOTDIR/bin/hbtranspiler}"
HBOUT="$SCRIPTDIR/hbout"
CSOUT="$SCRIPTDIR/csout"
PASS=0
FAIL=0

# Transpiled output lands in hbout/ and csout/ sibling directories
# instead of alongside each test*.prg. Keeps the tests/ tree readable
# — a git diff on the test suite shows .prg-only churn without
# dozens of autogenerated .hb/.cs entries mixing in. buildhb.sh,
# buildcs.sh, and verify_shortoverload.sh consume the outputs from
# the new locations.
mkdir -p "$HBOUT" "$CSOUT"

# Whole-codebase pre-scan: populate hbreftab.tab with signature
# information for every test*.prg before any -GT runs. This is what
# makes cross-file by-ref data available to single-file transpiles
# (see test19a.prg for the canonical example).
for f in "$SCRIPTDIR"/test*.prg; do
   "$TRANSPILER" -I"$ROOTDIR/include" -I"$SCRIPTDIR" "$f" -GF -q > /dev/null 2>&1
done

for f in "$SCRIPTDIR"/test*.prg; do
   name=$(basename "$f" .prg)
   "$TRANSPILER" -I"$ROOTDIR/include" -I"$SCRIPTDIR" -o"$HBOUT/" "$f" -GT 2>/dev/null
   if [ $? -eq 0 ]; then
      echo "PASS: $name"
      PASS=$((PASS + 1))
   else
      echo "FAIL: $name"
      FAIL=$((FAIL + 1))
   fi
done

# Re-emit the short-overload test pairs under -GS, then verify the
# emitter's gating and typing. Kept here rather than in buildcs.sh
# because the check doesn't need a dotnet toolchain — a grep over the
# emitted .cs is enough.
for p in test45a test45b test46a test46b; do
   [ -f "$SCRIPTDIR/$p.prg" ] || continue
   "$TRANSPILER" -I"$ROOTDIR/include" -I"$SCRIPTDIR" -o"$CSOUT/" \
                 "$SCRIPTDIR/$p.prg" -GS -q > /dev/null 2>&1
done
if [ -x "$SCRIPTDIR/verify_shortoverload.sh" ]; then
   if bash "$SCRIPTDIR/verify_shortoverload.sh"; then
      PASS=$((PASS + 1))
   else
      FAIL=$((FAIL + 1))
   fi
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
