// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbExpat.* name the application
// calls that HbExpat.cs does not implement. Each throws at call time.
// Implement the function in HbExpat.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbExpat
{
    public static dynamic XML_ErrorString(params dynamic[] args) => throw new NotImplementedException(nameof(XML_ErrorString));
    public static dynamic XML_GetCurrentLineNumber(params dynamic[] args) => throw new NotImplementedException(nameof(XML_GetCurrentLineNumber));
    public static dynamic XML_GetErrorCode(params dynamic[] args) => throw new NotImplementedException(nameof(XML_GetErrorCode));
    public static dynamic XML_Parse(params dynamic[] args) => throw new NotImplementedException(nameof(XML_Parse));
    public static dynamic XML_ParserCreate(params dynamic[] args) => throw new NotImplementedException(nameof(XML_ParserCreate));
    public static dynamic XML_SetCharacterDataHandler(params dynamic[] args) => throw new NotImplementedException(nameof(XML_SetCharacterDataHandler));
    public static dynamic XML_SetElementHandler(params dynamic[] args) => throw new NotImplementedException(nameof(XML_SetElementHandler));
    public static dynamic XML_SetUserData(params dynamic[] args) => throw new NotImplementedException(nameof(XML_SetUserData));
}
