// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every Xhb.* name the application
// calls that Xhb.cs does not implement. Each throws at call time.
// Implement the function in Xhb.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class Xhb
{
    public static dynamic hb_regexReplace(params dynamic[] args) => throw new NotImplementedException(nameof(hb_regexReplace));
    public static dynamic xhb_RTrim(params dynamic[] args) => throw new NotImplementedException(nameof(xhb_RTrim));
}
