// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test98.prg.

public static class Test98PrgConst
{
    public const long LAMP_LOW = 1L;
    public const long LAMP_OFF = 0L;
}
