// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test7.prg.

public static class Test7PrgConst
{
    public const string APP_VERSION = @"1.0";
    public const long MAX_ITEMS = 100L;
}
