// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test137.prg.

public static class Test137PrgConst
{
    public const long KIND_FCN = 1L;
    public const long KIND_ITEM = 2L;
}
