// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test82.prg.

public static class Test82PrgConst
{
    public const long BIGVAL = 4294967296L;
    public const decimal RATE = 1.5m;
    public const long SMALLFLAG = 7L;
}
