// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test29.prg.

public static class Test29PrgConst
{
    public const string HALT = @"HALT";
    public const string RUN = @"RUN";
    public const string SHUT = @"SHUTDOWN";
}
