// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test73.ch.

public static class Test73Const
{
    public const long TEST73_BASE_PANEL = 2L;
    public const string TEST73_DEFAULT_NAME = @"default-name";
}
