// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test25.prg.

public static class Test25PrgConst
{
    public const long MAGIC = 42L;
    public const decimal PI = 3.14m;
    public const string SEPARATOR = @"\";
}
