// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test47.ch.

public static class Test47Const
{
    public const long TEST47_BASE = 100L;
    public const long TEST47_COND = 42L;
    public const string TEST47_LABEL = @"filtered";
}
