// Auto-generated by src/transpiler/tools/gendefines.py
// Harvested from test44.ch.

public static class Test44Const
{
    public const string TEST44_GREETING = @"hello defines";
    public const long TEST44_LIMIT = 100L;
    public const long TEST44_OFFSET = 32L;
}
