// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbNf.* name the application
// calls that HbNf.cs does not implement. Each throws at call time.
// Implement the function in HbNf.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbNf
{
    public static dynamic ft_Elapsed(params dynamic[] args) => throw new NotImplementedException(nameof(ft_Elapsed));
}
