// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbCt.* name the application
// calls that HbCt.cs does not implement. Each throws at call time.
// Implement the function in HbCt.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbCt
{
    public static dynamic Ceiling(params dynamic[] args) => throw new NotImplementedException(nameof(Ceiling));
    public static dynamic DoY(params dynamic[] args) => throw new NotImplementedException(nameof(DoY));
    public static dynamic IsLeap(params dynamic[] args) => throw new NotImplementedException(nameof(IsLeap));
}
