// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbTip.* name the application
// calls that HbTip.cs does not implement. Each throws at call time.
// Implement the function in HbTip.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbTip
{
    public static dynamic tip_MailAssemble(params dynamic[] args) => throw new NotImplementedException(nameof(tip_MailAssemble));
}
