// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbHpdf.* name the application
// calls that HbHpdf.cs does not implement. Each throws at call time.
// Implement the function in HbHpdf.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbHpdf
{
    public static dynamic HPDF_AddPage(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_AddPage));
    public static dynamic HPDF_GetFont(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_GetFont));
    public static dynamic HPDF_Page_BeginText(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_BeginText));
    public static dynamic HPDF_Page_EndText(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_EndText));
    public static dynamic HPDF_Page_GetRGBFill(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_GetRGBFill));
    public static dynamic HPDF_Page_SetFontAndSize(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_SetFontAndSize));
    public static dynamic HPDF_Page_SetRGBFill(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_SetRGBFill));
    public static dynamic HPDF_Page_TextOut(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_TextOut));
    public static dynamic HPDF_Page_TextWidth(params dynamic[] args) => throw new NotImplementedException(nameof(HPDF_Page_TextWidth));
}
