// Auto-generated by easipos-transpiled's scripts/gen_library_stubs.py:
// a NotImplementedException stub for every HbMzip.* name the application
// calls that HbMzip.cs does not implement. Each throws at call time.
// Implement the function in HbMzip.cs and rerun the script to drop its
// stub. Do not edit this file.

using System;

public static partial class HbMzip
{
    public static dynamic hb_unzipClose(params dynamic[] args) => throw new NotImplementedException(nameof(hb_unzipClose));
    public static dynamic hb_unzipExtractCurrentFile(params dynamic[] args) => throw new NotImplementedException(nameof(hb_unzipExtractCurrentFile));
    public static dynamic hb_unzipFileFirst(params dynamic[] args) => throw new NotImplementedException(nameof(hb_unzipFileFirst));
    public static dynamic hb_unzipFileInfo<T1>(dynamic p0, ref T1 p1) => throw new NotImplementedException(nameof(hb_unzipFileInfo));
    public static dynamic hb_unzipFileNext(params dynamic[] args) => throw new NotImplementedException(nameof(hb_unzipFileNext));
    public static dynamic hb_unzipOpen(params dynamic[] args) => throw new NotImplementedException(nameof(hb_unzipOpen));
    public static dynamic hb_zipClose(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zipClose));
    public static dynamic hb_zipOpen(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zipOpen));
    public static dynamic hb_zipStoreFile(params dynamic[] args) => throw new NotImplementedException(nameof(hb_zipStoreFile));
}
