// NetSurface: write the transpiler's --extern= table from .NET assemblies.
//
//   dotnet run --project tools/netsurface -- <out.tab> <assembly.dll>...
//
// A Harbour program reaches its COM shims through win_oleCreateObject();
// in C# it calls each shim's .NET build directly. The transpiler then has
// to know the class and its methods: which parameters are `out` or `ref`
// (Harbour's `@` is one mechanism, C# has two), their types and the
// return types. This tool reads them from each assembly's metadata
// (MetadataLoadContext: nothing is loaded or run, so the shim's own
// dependencies need not be present) and writes them in the reftab's row
// format, as hbreftab.c's loader reads them:
//
//   EasiSI                      X  EasiPos.EasiSI.EasiSI  0
//   EasiSI::EasiSI__Version     -  STRING                 0
//   EasiSI::EasiSI__SystemInfo  N  -                      11  pcName:STRING:TU ...
//
// A class is every public, non-abstract class marked [ComVisible(true)],
// the ones a ProgID creates; its Harbour name is its simple name. Its
// methods are its public instance methods. Row flag X marks a .NET class
// (RETTYPE is its C# name), N a method with no value; pflag T says the
// type is declared (callers do not refine it), U an `out` parameter, R a
// `ref` one.
//
// What cannot be expressed fails the run, naming it: a type with no
// Harbour equivalent here, a public property, two methods of one name
// (Harbour has no overloads), or a class with no methods. Exit 1.

using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;

if (args.Length < 2)
{
    Console.Error.WriteLine("usage: NetSurface <out.tab> <assembly.dll>...");
    return 2;
}

var outPath = args[0];
var assemblies = args.Skip(1).Select(Path.GetFullPath).ToList();
var errors = new List<string>();
var rows = new List<string>();

// The runtime's own assemblies, and each assembly's directory, resolve
// the types the metadata names.
var paths = Directory.GetFiles(RuntimeEnvironment.GetRuntimeDirectory(), "*.dll")
    .Concat(assemblies.SelectMany(a => Directory.GetFiles(Path.GetDirectoryName(a)!, "*.dll")))
    .Distinct(StringComparer.OrdinalIgnoreCase);
using var context = new MetadataLoadContext(new PathAssemblyResolver(paths));

foreach (var path in assemblies)
{
    var assembly = context.LoadFromAssemblyPath(path);
    var classes = assembly.GetTypes()
        .Where(t => t.IsClass && t.IsPublic && !t.IsAbstract && IsComVisible(t))
        .OrderBy(t => t.Name, StringComparer.Ordinal);
    foreach (var type in classes)
        Describe(type, Path.GetFileName(path));
}

if (errors.Count > 0)
{
    foreach (var error in errors)
        Console.Error.WriteLine("NetSurface: " + error);
    return 1;
}

var text = new StringBuilder();
text.Append("# The transpiler's --extern= table: the .NET classes the program reaches\n");
text.Append("# (its COM shims' .NET builds), in the reftab's row format. Row flag X: a\n");
text.Append("# .NET class, RETTYPE its C# name. pflags: T declared type, U out, R ref.\n");
text.Append("#\n");
text.Append("# THIS FILE IS GENERATED by harbour-core src/transpiler/tools/netsurface from\n");
foreach (var path in assemblies)
    text.Append("#   " + Path.GetFileName(path) + "\n");
foreach (var row in rows)
    text.Append(row).Append('\n');
File.WriteAllText(outPath, text.ToString());
Console.WriteLine($"NetSurface: {rows.Count} rows from {assemblies.Count} assemblies into {outPath}");
return 0;

void Describe(Type type, string file)
{
    var cls = type.Name;
    rows.Add($"{cls}\tX\t{type.FullName}\t0");

    foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
        errors.Add($"{file}: {type.FullName}.{property.Name}: a property; only methods are described");

    var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
        .Where(m => !m.IsSpecialName)
        .OrderBy(m => m.Name, StringComparer.Ordinal)
        .ToList();
    if (methods.Count == 0)
        errors.Add($"{file}: {type.FullName}: no public methods");

    foreach (var group in methods.GroupBy(m => m.Name, StringComparer.OrdinalIgnoreCase))
    {
        if (group.Count() > 1)
        {
            errors.Add($"{file}: {type.FullName}.{group.Key}: overloaded; Harbour has one routine per name");
            continue;
        }
        var method = group.Single();
        var isVoid = method.ReturnType.FullName == "System.Void";
        var ret = isVoid ? "-" : HarbourType(method.ReturnType, $"{type.FullName}.{method.Name}: return", file);
        var parms = method.GetParameters();
        var row = new StringBuilder($"{cls}::{cls}__{method.Name}\t{(isVoid ? "N" : "-")}\t{ret}\t{parms.Length}");
        foreach (var p in parms)
        {
            var byRef = p.ParameterType.IsByRef;
            var pType = byRef ? p.ParameterType.GetElementType()! : p.ParameterType;
            var flags = "T" + (byRef ? (p.IsOut ? "U" : "R") : "");
            row.Append($"\t{p.Name}:{HarbourType(pType, $"{type.FullName}.{method.Name}: parameter {p.Name}", file)}:{flags}");
        }
        rows.Add(row.ToString());
    }
}

// The reftab's type tags, each a C# type the transpiler maps back exactly
// (hb_csTypeMap). A type outside them would bind to the wrong C# type.
string HarbourType(Type type, string where, string file)
{
    switch (type.FullName)
    {
        case "System.String": return "STRING";
        case "System.Int64": return "INTEGER";
        case "System.Decimal": return "NUMERIC";
        case "System.Boolean": return "LOGICAL";
        case "System.DateTime": return "TIMESTAMP";
        case "System.DateOnly": return "DATE";
        case "System.Object": return "USUAL";
    }
    errors.Add($"{file}: {where}: {type.FullName} has no Harbour type here (string, long, decimal, bool, DateTime, DateOnly, object)");
    return "USUAL";
}

static bool IsComVisible(Type type) =>
    type.CustomAttributes.Any(a =>
        a.AttributeType.FullName == "System.Runtime.InteropServices.ComVisibleAttribute" &&
        a.ConstructorArguments.Count == 1 && a.ConstructorArguments[0].Value is true);
